### ISSUE TITLE
Basic AccountService to handle Account Creation and Login

### ISSUE THREAD

**Issue by khoiphan21** [khoiphan21/sourcestash#1]
## User Story
As a **new user**, I want to **see if my details are valid while creating a new account** so that I can **fix any typo mistakes, or input mistakes that I may have made, and so can create an account faster**

## Tasks
AccountService to handle these tasks:

### Account Creation
- [x] (Angular) Send registration details to server
- [x] (Angular) Display a message if the registration is unsuccessful
- [x] (AppServer) query database for availability of an email address
- [x] (AppServer) query database for password of a user to check
- [x] Added some basic tests for the Service

### Log in
- [x] (Angular) send email and password to server for confirmation
- [x] (AppServer) query database for username and password, then authenticate the user
- [x] (Functionality) The page can 'log in' with a username and password now

### Form Validation
- [x] Implement code to check with the Application Server (when user finished typing the email) to see if the email address as id is available
- [x] send back the reply to the Component for the component to display an error if there is one
Application Server features needed:
- [x] receive a 'email check' request, check with the database if the email is available, then return the status code

**Comment by jeremyng5352** [comment]
- [ ] dsadasdasdaslkdas
