### ISSUE TITLE
Intuitive Profile Design

### ISSUE THREAD

**Issue by HaydenOtto** [khoiphan21/sourcestash#10]
## User story
As a **user**, I want to **view my profile more intuitively** so that I can **easily find my stashes, favourites and sources; also need to be able to edit my account info**

## Tasks
- [x] Refine profile design from the mockups. 
   - [x] Get user info (stashes, sources, favourites) from database to load on profile.
   - [x] Load and display account info (including display picture) on profile.
   - [x] Ensure account info is editable by user from this page. # #
