### ISSUE TITLE
Source and Stash popup page interface coding

### ISSUE THREAD

**Issue by khoiphan21** [khoiphan21/sourcestash#11]
## User Story
As a **user**, I want to **store a source in my stash** so that I can **organize it and view it later**

## Task
**Source** and **Stash** generation interface

- [x] Interface for a creating stash
- [x] Interface for a creating source
- [x] Basic popup for viewing a source

**Comment by jeremyng5352** [comment]
# User Story
As a USER, I want to CREATE A STASH so that I can STORE MY SOURCES
# Task
SOURCE generation feature in a STASH
