### ISSUE TITLE
Design dashboard mockup

### ISSUE THREAD

**Issue by khoiphan21** [khoiphan21/sourcestash#114]
## User Story
- As a user, I want to be able to create a new board on my dashboard
- As a user, I want to be able to rename, delete, or change the cover photo of an existing board 
- As a user, I want to be able to save or cancel any current changes I've made to a board
- As a user, I want to be able to click on a board to view its contents

## Tasks
- [x] Design basic elements 
    - [x] Page heading
    - [x] Edit, save, and cancel buttons
    - [x] Create board button
- [x] Design mockup with no boards
- [x] Design mockup with edit board option
