### ISSUE TITLE
Paper Prototype

### ISSUE THREAD

**Issue by huynhj26** [khoiphan21/sourcestash#115]
## User story
As a user, I want to get from the homepage page to my board and add my links in the most convenient 

## Tasks
- [x] sketch the dashboard
- [x] sketch personal board 
- [x] sketch cards
- [x] sketch expansions of links
- [x] sketch preview
