### ISSUE TITLE
Prototype Testing with Users and Define Name

### ISSUE THREAD

**Issue by huynhj26** [khoiphan21/sourcestash#128]
## User Story
As a user, I want to intuitively build my library of links so that I can find them easily

Link to online form
https://goo.gl/forms/rwAezyKVZ5Z2cwyr1

## Tasks
- [ ] Test with 10 student users
- [ ] Test with 10 non-student users
- [ ] Do a report showing comments, feedbacks and user difficulties
