### ISSUE TITLE
Design mockups for boards

### ISSUE THREAD

**Issue by steve-crabsticks17864** [khoiphan21/sourcestash#130]
## User Story
- As a user, I want to be able to change the name of my board
- As a user, I want to be create a new card and name it to whatever I'd like it to be
- As a user, I want to be able to add a new link to a card and add a name for it
- As a user, I want to be able to edit the links in my card by deleting, reordering, or editing them
- As a user, I want to be able to rename or delete my card
- As a user, I want to be able to preview each link to have an idea of what it's about

## Tasks
- [x] Create mockups for various scenarios
    - [x] A board with no cards
    - [x] Creating a new card
    - [x] Adding a new link to a card
    - [x] Minimised view of a card
    - [x] Collapsed view of a card
    - [x] Editing the links on a board
    - [x] Links with a preview of the link
    - [x] Editing the name of a board
