### ISSUE TITLE
Define the Market

### ISSUE THREAD

**Issue by huynhj26** [khoiphan21/sourcestash#133]
## Task
- [x] Develop Unfair Advantage
- [x] Design Channels 
- [x] Develop Customer Segments
- [x] Define Revenue Streams
