### ISSUE TITLE
User Testing

### ISSUE THREAD

**Issue by huynhj26** [khoiphan21/sourcestash#135]
## Aim
To identify use issues 
To identify most profitable market
To find a name that people associate with

## Task
- [ ] Test with 5 Students
- [ ] Test with 5 non-students
- [ ] Test different names on survey
