### ISSUE TITLE
Source Drag & Drop - 1

### ISSUE THREAD

**Issue by khoiphan21** [khoiphan21/sourcestash#14]
# User Story 
As a USER, I want to MOVE THE SOURCES AROUND THE STASH TO ORGANIZE THEM

# Task 
## Rendering
- [x] Find out how to render a component/element **relative** to another, based on a value passed by .ts file
- [x] Creating paths between two components

## Integration with Service
- [x] Call method to retrieve child sources
