### ISSUE TITLE
UI for Adding Collaborators

### ISSUE THREAD

**Issue by khoiphan21** [khoiphan21/sourcestash#16]
## User Story
As a **stash owner**, I want to **add someone else as a collaborator** so that **they can make changes to the stash I own**

## Tasks
- [ ] put an estimate to this issue
- [ ] 'Add Collaborator' button in a Stash's UI 
- [ ] Design the popup for 'Add Collaborator' feature
