### ISSUE TITLE
Search bar UI for every page

### ISSUE THREAD

**Issue by jeremyng5352** [khoiphan21/sourcestash#25]
## User story
As a **user**, I want to **access the search function on every page** so that I can **search things up quickly**

## Tasks
- [x] Design a search bar for the header 
- [x] Implement search bar on the website in HTML/CSS.
- [ ] Ensure search bar is able to find items with the appropriate tag/title from the SourceStash database.
