### ISSUE TITLE
Professional Design for Login/Sign up page

### ISSUE THREAD

**Issue by jeremyng5352** [khoiphan21/sourcestash#26]
## User Story
As a **new user**, I want to **view a modern and professional design of the welcome page** so that **I am interested in reading more about SourceStash**

## Tasks
- [x] First Version (Hayden)
- [x] Second Version (Khoi)
  - [x]  Reviewed by Hayden
  - [x] Reviewed by Jeremy
