### ISSUE TITLE
Database to store user information

### ISSUE THREAD

**Issue by khoiphan21** [khoiphan21/sourcestash#28]
## User Story
As a **new user**, I want to **create a new account with email and password**, so that **I can start storing stashes and view them**

## Tasks
- [x] Create Google Cloud SQL MySQL server to host information
- [x] Create a node.js server that can connect to the Cloud SQL instance
- [x] Setup a phpmyadmin server in the project to manage MySQL server
- [x] (DATABASE) table to store user information: email, password, first name, last name and id (initially created from email) 
- [x] A frame for AccountService that handles connecting to the server for authentication
- [x] Established connection between the AccountService-Application Server
- [x] Established connection between the Application Server and the Cloud MySQL database
