### ISSUE TITLE
Database design for storing advanced Sources' information

### ISSUE THREAD

**Issue by khoiphan21** [khoiphan21/sourcestash#31]
## User Story
As a **user contributing to a stash**, I want to **move the sources around the stash** so that I can **organize them**

## Tasks
- [x] [ALGORITHM] design a way for stashes to be displayed in the user interface
- [x] update the database table for sources information
- [x] Work with Jeremy to implement the new system into the real UI
