### ISSUE TITLE
Database Service for Adding Collaborators

### ISSUE THREAD

**Issue by khoiphan21** [khoiphan21/sourcestash#36]
## User Story
As a **stash owner**, I want to **add someone else as a collaborator** so that **they can make changes to the stash I own**

## Tasks
- [x] Table with stash id as primary key, and user ids as collaborator's ids
- [x] Application Server with method to update the list of collaborators in the database
  - [x] Update the list of collaborators for a stash (handles both adding and removing)
  - [x] API to retrieve all collaborators for a stash
