### ISSUE TITLE
Angular UI & Service for Adding Collaborators

### ISSUE THREAD

**Issue by khoiphan21** [khoiphan21/sourcestash#37]
## User Story
As a **stash owner**, I want to **add someone else as a collaborator** so that **they can make changes to the stash I own**

## Tasks
- [x] Design this service 
  - [x] View the list of current collaborators
  - [x] Adding a new Collaborator
  - [x] Remove a Collaborator
- [x] Test this service (NEED MORE DETAILS)
  - [x] Test getting shared stashes
  - [x] Test retrieving collaborators
  - [x] Test adding new collaborator
  - [x] Test updating list of collaborator
  - [x] Test deleting a collaborator
- [x] UI for adding collaborators
  - [x] New section inside 'Edit stash'
  - [x] Showing a list of collaborators + 'delete' button
  - [x] With new section to add a new collaborator
- [x] (UI stuff)
  - [x] When the user logged in, retrieve all collaborating stashes as well
  - [x] Show the list of collaborators in stash page
  - [x] Display 'owned' and 'shared with me' stashes differently
