### ISSUE TITLE
Rework the designs, starting with Wireframes

### ISSUE THREAD

**Issue by HaydenOtto** [khoiphan21/sourcestash#42]
Page and functionality mockups must be refined for website implementation.

## Tasks
- [x] Wireframe for Welcome page
- [x] Wireframe for 'create an account' page
- [x] Wireframe Stashes Page
- [x] Wireframe for Home Page
- [x] Wireframe for Profile Page

- [x] Updates
  - [x] Sidebar on the Stash Page
  - [x] Wireframe log in. Remove sign up and perfect log in with Google.
  - [x] Finalise Stash Editor and Source editor.

## Criteria
- Done when all members have agreed to the final wireframe layout
