### ISSUE TITLE
Social Login with Google

### ISSUE THREAD

**Issue by khoiphan21** [khoiphan21/sourcestash#43]
# User Story
As a **new user**, I want to **create an account and login with two clicks**, given that **I have logged in to my google account.

# Tasks
- [x] Authentication: Oauth for Google+ on server side
  - [x] Server can connect to Google OAuth2 API
  - [x] Angular App can connect to Google OAuth2 APi
  - [x] Angular App can retrieve the user's Google etag
  - [x] Angular App can log a user in after logged in with Google
- [x] Server login for "Google Login" api
- [x] Storing new user information based on "Google signup" api
