### ISSUE TITLE
Wireframes for essential Popups

### ISSUE THREAD

**Issue by khoiphan21** [khoiphan21/sourcestash#45]
# Tasks
- [x] Popup for creating a stash
- [x] popup for Source Editor
  - [x] Fix up the content

**Comment by HaydenOtto** [comment]
Combined both tasks into one by making a 'stash editor' pop up.
