### ISSUE TITLE
Professional, final design for Welcome Page

### ISSUE THREAD

**Issue by khoiphan21** [khoiphan21/sourcestash#46]
## Tasks
- [x] First Version (Hayden)
- [x] Second Version (Khoi)
  - [x]  Reviewed by Hayden
  - [x] Reviewed by Jeremy
