### ISSUE TITLE
Sources Drag & Drop - 2

### ISSUE THREAD

**Issue by khoiphan21** [khoiphan21/sourcestash#47]
# User Story 
As a USER, I want to MOVE THE SOURCES AROUND THE STASH TO ORGANIZE THEM

# Task 
## Updating
- [x] Find out: drag and drop a component, and update the position values of the [model]. Idea: at startdrag, record initial position; at enddrag, record final position. Update x-position value by enddrag.x - startdrag.x (or something like that)

## Integration with Service
- [x] Call update method when child source changes position
- [x] Find the 'relative' position of the source
- [x] Service updates the database on the new position of the source
