### ISSUE TITLE
Automatically load information of stashes belonging to a user

### ISSUE THREAD

**Issue by khoiphan21** [khoiphan21/sourcestash#52]
## User Story
As a **logged in user**, I want to **immediately see the stashes belonging to me when I click on the profile page** so that I can **start editing them immediately**

## Tasks
- [ ] Account Service to retrieve all stashes for a user when user is logged in
- [ ] Update profile page to retrieve the loaded stashes from the Account Service 
- [ ] Update stashes page to receive a stash and its sources (?) to display
