### ISSUE TITLE
Notify the user when unable to connect to the server

### ISSUE THREAD

**Issue by khoiphan21** [khoiphan21/sourcestash#53]
## User Story
As a **logged in user trying to use Source Stash**, I want to **get updated immediately when the app fails to connect to the server** so that **I know the problem does not lie with the app but with internet connection**

## Task
- [ ] Small Component at the bottom of root page that shows up when the connection to the server failed
- [ ] Code to first check connection with the server when the app started
- [ ] Component listening to a service's event to respond whenever connection is cut off
