### ISSUE TITLE
Professional Design for Stash Page

### ISSUE THREAD

**Issue by khoiphan21** [khoiphan21/sourcestash#55]
## Tasks
- [x] First Version (Hayden)
  - [x] Design how a source looks
  - [x] Design the 'links' between the sources
  - [x] Sidebar: Info, Sources, Comment (3 tabs)
- [x] Second Version (Khoi)
  - [x] Reviewed by Hayden
  - [x] Reviewed by Jeremy
