### ISSUE TITLE
Professional Design for Profile Page

### ISSUE THREAD

**Issue by khoiphan21** [khoiphan21/sourcestash#59]
## Tasks
- [x] First Version (Hayden)
  - [x] Profile page only supports viewing your own stashes
  - [x] "Add Stash" button
- [x] Second Version (Khoi)
  - [x]  Reviewed by Hayden
  - [x] Reviewed by Jeremy
