### ISSUE TITLE
Minor bug fixes

### ISSUE THREAD

**Issue by khoiphan21** [khoiphan21/sourcestash#72]
## Tasks
- [x] Fix up bug when doing social-login: the system loads first before user selected the account
- [x] Retrieve the tags for a source when the source is loaded
- [x] Fix the issue with source flying around after being viewed
- [x] Fix issue with sources not getting rendered correctly on smaller screens
- [x] Fix issue with some source not being rendered at the correct position
- [x] Fixed issues with showing random stuff for root source and not description
- [x] Show tags for each source in source-edit
- [x] Fix issues with lines not being re-drawn after source editted
- [x] Header not clickable in a stashpage
- [x] change Services in Angular Service to check for parameters before querying the server
- [x] change all services to use Promise instead
- [x] Fix the z-index of sources (right now they can float on top of GUI)
- [x] Change mysql statements in the server backend to use mysqlPromise instead
- [x] Do not show the 'root' source on the side bar
- [x] error with GoogleAPIService: 'init' not defined
