### ISSUE TITLE
Mobile Page Mockups

### ISSUE THREAD

**Issue by HaydenOtto** [khoiphan21/sourcestash#79]
### Tasks
- [x] Welcome Page Mockup
- [] Profile Page Mockup
- [] Stashes Page Mockup
- [] Sign up Page Mockup
- [] Home Page Mockup
