### ISSUE TITLE
Deleting Sources

### ISSUE THREAD

**Issue by khoiphan21** [khoiphan21/sourcestash#99]
## User Story
As a **content generator**, I want to **delete any source I don't need** so that I can **better organize the sources in my stash**

## Tasks
- [x] Add "Delete" button to each source
- [x] Connect UI to service
- [x] Testing for UI bugs
